Prefer local nix-index if present
nix-community/comma pull request #7
Opened 2020-08-13 19:58 UTC by fzakaria

The nix-index database offered in the derivation may be more out of date than what is present on the system.

In fact, prefer any local nix-index database to the prebuilt database included with comma

fixes #6

2020-11-19 14:11 UTC, siraben requested changes

2020-11-19 14:11 UTC, siraben commented on .gitignore
> +# ignore nix-build result folter
Typo, `folter` -> `folder`

2020-11-19 17:08 UTC, fzakaria commented on .gitignore
> +# ignore nix-build result folter
```suggestion
# ignore nix-build result folder
```

2020-11-19 17:09 UTC, siraben approved these changes

2021-09-21 13:31 UTC, thenonameguy approved these changes

2022-01-02 17:11 UTC, merged

2022-01-02 17:42 UTC, fzakaria commented
Yay! Maintainers :)

Does this integrate with the nightly builds @Mic92 generates ? 

If not I am happy to upstream that contribution as well.

2022-01-02 17:47 UTC, Artturin commented
i updated the built-in index to the weekly update in https://github.com/nix-community/comma/commit/c9b070ca6d1e857d96765a435c455e79afb5b490
but it isn't automatic

PRs are welcome

2022-01-02 18:01 UTC, Mic92 commented
> Yay! Maintainers :)
> 
> Does this integrate with the nightly builds @Mic92 generates ?
> 
> If not I am happy to upstream that contribution as well.

What nightly builds are you talking about?